INSERT INTO attribute_desc VALUES(2001,5001,'en','Agent-Based Model Analysis','Agent-Based Model Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2001,5001,'es','Analisis de modelos basados en agentes','Análisis de modelos basados en agentes',NULL,NULL);
INSERT INTO attribute_desc VALUES(2002,5001,'en','Archival Analysis','Archival Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2002,5001,'es','Analisis de Archivo','Análisis de Archivo',NULL,NULL);
INSERT INTO attribute_desc VALUES(2003,5001,'en','Bibliometrics and Scientometrics','Bibliometrics and Scientometrics',NULL,NULL);
INSERT INTO attribute_desc VALUES(2003,5001,'es','Bibliometria y cienciometria','Bibliometría y cienciometría',NULL,NULL);
INSERT INTO attribute_desc VALUES(2004,5001,'en','Bioinformatics Tools','Bioinformatics Tools',NULL,NULL);
INSERT INTO attribute_desc VALUES(2004,5001,'es','Herramientas bioinformaticas','Herramientas bioinformáticas',NULL,NULL);
INSERT INTO attribute_desc VALUES(2005,5001,'en','Cluster Analysis','Cluster Analysis, k-Means Clustering',NULL,NULL);
INSERT INTO attribute_desc VALUES(2005,5001,'es','Analisis de Conglomerados','Análisis de Conglomerados, Clusterización con k-medias',NULL,NULL);
INSERT INTO attribute_desc VALUES(2006,5001,'en','Computational Qualitative Analysis','Computational Qualitative Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2006,5001,'es','Analisis Cualitativo Computacional','Análisis Cualitativo Computacional',NULL,NULL);
INSERT INTO attribute_desc VALUES(2007,5001,'en','Correspondence Analysis','Correspondence Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2007,5001,'es','Analisis de Correspondencia','Análisis de Correspondencia',NULL,NULL);
INSERT INTO attribute_desc VALUES(2008,5001,'en','Digital Source Mining','Digital Source Mining',NULL,NULL);
INSERT INTO attribute_desc VALUES(2008,5001,'es','Mineria de Fuentes Digitales','Minería de Fuentes Digitales',NULL,NULL);
INSERT INTO attribute_desc VALUES(2009,5001,'en','Direct Observation of Behavior','Direct Observation of Behavior',NULL,NULL);
INSERT INTO attribute_desc VALUES(2009,5001,'es','Observacion directa','Observación directa del comportamiento',NULL,NULL);
INSERT INTO attribute_desc VALUES(2010,5001,'en','Document Analysis','Document Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2010,5001,'es','Analisis documental','Análisis Documental',NULL,NULL);
INSERT INTO attribute_desc VALUES(2011,5001,'en','Ethnography','Ethnography',NULL,NULL);
INSERT INTO attribute_desc VALUES(2011,5001,'es','Etnografia','Etnografía',NULL,NULL);
INSERT INTO attribute_desc VALUES(2012,5001,'en','Formal Concept Analysis','Formal Concept Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2012,5001,'es','Analisis de conceptos formales','Análisis de Conceptos Formales',NULL,NULL);
INSERT INTO attribute_desc VALUES(2013,5001,'en','Genetic Analysis','Genetic Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2013,5001,'es','Analisis genetico','Análisis Genético',NULL,NULL);
INSERT INTO attribute_desc VALUES(2014,5001,'en','Inductive Game Theory','Inductive Game Theory',NULL,NULL);
INSERT INTO attribute_desc VALUES(2014,5001,'es','Teoria de juegos inductiva','Teoría de juegos inductiva',NULL,NULL);
INSERT INTO attribute_desc VALUES(2015,5001,'en','Interviews','Interviews',NULL,NULL);
INSERT INTO attribute_desc VALUES(2015,5001,'es','Entrevistas','Entrevistas',NULL,NULL);
INSERT INTO attribute_desc VALUES(2016,5001,'en','Linear Regression','Linear and Logistic Regression, Event Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2016,5001,'es','Regresiones lineales','Regresiones lineales, logísticas y análisis de eventos',NULL,NULL);
INSERT INTO attribute_desc VALUES(2017,5001,'en','Literature Review','Literature Review',NULL,NULL);
INSERT INTO attribute_desc VALUES(2017,5001,'es','Revision bibliografica','Revisión Bibliográfica',NULL,NULL);
INSERT INTO attribute_desc VALUES(2018,5001,'en','Machine Learning','Machine Learning and Fundamental Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2018,5001,'es','Aprendizaje de maquina','Aprendizaje de máquina y análisis fundamental',NULL,NULL);
INSERT INTO attribute_desc VALUES(2019,5001,'en','Multiplex Network Analysis','Monoplex, Multiplex, or Multilayer Network Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2019,5001,'es','Analisis multiplex','Análisis Monoplex,  multiplex o multicapa',NULL,NULL);
INSERT INTO attribute_desc VALUES(2020,5001,'en','Network Visualization','Network Analysis and Visualization',NULL,NULL);
INSERT INTO attribute_desc VALUES(2020,5001,'es','Visualizacion de redes','Análisis y Visualización de redes',NULL,NULL);
INSERT INTO attribute_desc VALUES(2021,5001,'en','Pattern Recognition','Pattern Recognition for Distant Reading',NULL,NULL);
INSERT INTO attribute_desc VALUES(2021,5001,'es','Reconocimiento de patrones','Reconocimiento de patrones para lectura distante',NULL,NULL);
INSERT INTO attribute_desc VALUES(2022,5001,'en','Reconstruction of Genealogies and Trajectories','Reconstruction of Genealogies and Trajectories',NULL,NULL);
INSERT INTO attribute_desc VALUES(2022,5001,'es','Reconstrucccion de genealogias y trayectorias','Reconstruccción de genealogías y trayectorias',NULL,NULL);
INSERT INTO attribute_desc VALUES(2023,5001,'en','Sentiment Analysis','Sentiment Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2023,5001,'es','Analisis de sentimientos','Análisis de sentimientos',NULL,NULL);
INSERT INTO attribute_desc VALUES(2024,5001,'en','Software Engineering','Software Engineering',NULL,NULL);
INSERT INTO attribute_desc VALUES(2024,5001,'es','Ingenieria de software','Ingeniería de Software',NULL,NULL);
INSERT INTO attribute_desc VALUES(2025,5001,'en','Social Networks Analysis','Study and Analysis of Social Networks',NULL,NULL);
INSERT INTO attribute_desc VALUES(2025,5001,'es','Analisis de redes sociales','Estudio y Análisis de redes sociales',NULL,NULL);
INSERT INTO attribute_desc VALUES(2026,5001,'en','Surveys','Surveys',NULL,NULL);
INSERT INTO attribute_desc VALUES(2026,5001,'es','Encuestas','Encuestas',NULL,NULL);
INSERT INTO attribute_desc VALUES(2027,5001,'en','Technical Analysis','Technical Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2027,5001,'es','Analisis Tecnico','Análisis Técnico',NULL,NULL);
INSERT INTO attribute_desc VALUES(2028,5001,'en','Topic Modeling Analysis','Topic Modeling Analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2028,5001,'es','Analisis de Modelos tematicos','Análisis de Modelos temáticos',NULL,NULL);
INSERT INTO attribute_desc VALUES(2029,5001,'en','Academic networks','Academic networks',NULL,NULL);
INSERT INTO attribute_desc VALUES(2029,5001,'es','Redes academicas','Redes académicas',NULL,NULL);
INSERT INTO attribute_desc VALUES(2030,5001,'en','CT indicators','CT indicators',NULL,NULL);
INSERT INTO attribute_desc VALUES(2030,5001,'es','Indicadores de CyT','Indicadores de CyT',NULL,NULL);
INSERT INTO attribute_desc VALUES(2031,5001,'en','Enviromental and climate change','Enviromental and Climate change',NULL,NULL);
INSERT INTO attribute_desc VALUES(2031,5001,'es','Cambio ambiental y climatico','Cambio ambiental y climático',NULL,NULL);
INSERT INTO attribute_desc VALUES(2032,5001,'en','Collective processing of information','Collective processing of information',NULL,NULL);
INSERT INTO attribute_desc VALUES(2032,5001,'es','Procesamiento colectivo de informacion','Procesamiento colectivo de información',NULL,NULL);
INSERT INTO attribute_desc VALUES(2033,5001,'en','Complex social systems','Complex social systems',NULL,NULL);
INSERT INTO attribute_desc VALUES(2033,5001,'es','Sistemas Sociales Complejos y Dinamicas Sociales','Sistemas Sociales Complejos y Dinámicas Sociales',NULL,NULL);
INSERT INTO attribute_desc VALUES(2034,5001,'en','Computational analysis','Computational analysis',NULL,NULL);
INSERT INTO attribute_desc VALUES(2034,5001,'es','Analisis Computacional','Análisis Computacional',NULL,NULL);
INSERT INTO attribute_desc VALUES(2035,5001,'en','Computational thinking','Computational Thinking',NULL,NULL);
INSERT INTO attribute_desc VALUES(2035,5001,'es','Pensamiento Computacional','Pensamiento Computacional',NULL,NULL);
INSERT INTO attribute_desc VALUES(2036,5001,'en','Gender studies','Gender studies',NULL,NULL);
INSERT INTO attribute_desc VALUES(2036,5001,'es','Estudios de Genero','Estudios de Género',NULL,NULL);
INSERT INTO attribute_desc VALUES(2037,5001,'en','Genealogy of Academic Entities','Genealogy of Academic Entities and Spaces',NULL,NULL);
INSERT INTO attribute_desc VALUES(2037,5001,'es','Genealogia de las entidades y los espacios academicos',' Genealogía de las entidades y los espacios académicos',NULL,NULL);
INSERT INTO attribute_desc VALUES(2038,5001,'en','General theory of social systems','General theory of social systems',NULL,NULL);
INSERT INTO attribute_desc VALUES(2038,5001,'es','Teoria general de Sistemas Sociales','Teoría general de Sistemas Sociales',NULL,NULL);
INSERT INTO attribute_desc VALUES(2039,5001,'en','Geographies of science','Geographies of Science',NULL,NULL);
INSERT INTO attribute_desc VALUES(2039,5001,'es','Geografias de la ciencia','Geografías de la ciencia',NULL,NULL);
INSERT INTO attribute_desc VALUES(2040,5001,'en','History of knowledge circulation','History of Knowledge Circulation',NULL,NULL);
INSERT INTO attribute_desc VALUES(2040,5001,'es','Historia de la circulacion del conocimiento','Historia de la circulación del conocimiento',NULL,NULL);
INSERT INTO attribute_desc VALUES(2041,5001,'en','History of probability','History of Probability',NULL,NULL);
INSERT INTO attribute_desc VALUES(2041,5001,'es','Historia de la probabilidad','Historia de la probabilidad',NULL,NULL);
INSERT INTO attribute_desc VALUES(2042,5001,'en','History of statistics','History of Statistics',NULL,NULL);
INSERT INTO attribute_desc VALUES(2042,5001,'es','Historia de la Estadistica','Historia de la Estadística',NULL,NULL);
INSERT INTO attribute_desc VALUES(2043,5001,'en','Institutionalization of statistics','Institutionalization of Statistics',NULL,NULL);
INSERT INTO attribute_desc VALUES(2043,5001,'es','Institucionalizacion de la estadistica','Institucionalización de la estadística',NULL,NULL);
INSERT INTO attribute_desc VALUES(2044,5001,'en','Knowledge representations','Knowledge representations',NULL,NULL);
INSERT INTO attribute_desc VALUES(2044,5001,'es','Representaciones del Conocimiento','Representaciones del Conocimiento',NULL,NULL);
INSERT INTO attribute_desc VALUES(2045,5001,'en','Maps of science','Maps of science',NULL,NULL);
INSERT INTO attribute_desc VALUES(2045,5001,'es','Mapas de la ciencia','Mapas de la ciencia',NULL,NULL);
INSERT INTO attribute_desc VALUES(2046,5001,'en','Mathematical modeling','Mathematical modeling and knowledge representation',NULL,NULL);
INSERT INTO attribute_desc VALUES(2046,5001,'es','Modelizacion Matematica','Modelización matemática y representacción del conocimiento científico',NULL,NULL);
INSERT INTO attribute_desc VALUES(2047,5001,'en','Quantitative History','Quantitative History',NULL,NULL);
INSERT INTO attribute_desc VALUES(2047,5001,'es','Historia cuantitativa','Historia cuantitativa',NULL,NULL);
INSERT INTO attribute_desc VALUES(2048,5001,'en','Reproduction of Academic Spaces','Reproduction of Academic Spaces',NULL,NULL);
INSERT INTO attribute_desc VALUES(2048,5001,'es','Reproduccion de espacios academicos','Reproducción de espacios académicos',NULL,NULL);
INSERT INTO attribute_desc VALUES(2049,5001,'en','Social Behavior','Social Behavior',NULL,NULL);
INSERT INTO attribute_desc VALUES(2049,5001,'es','Conducta social','Conducta social',NULL,NULL);
INSERT INTO attribute_desc VALUES(2050,5001,'en','Social categories and classifications','Social Categories and Classifications',NULL,NULL);
INSERT INTO attribute_desc VALUES(2050,5001,'es','Categorias y Clasificaciones sociales','Categorías y Clasificaciones sociales',NULL,NULL);
INSERT INTO attribute_desc VALUES(2051,5001,'en','Social complexity','Social Complexity',NULL,NULL);
INSERT INTO attribute_desc VALUES(2051,5001,'es','Complejidad social','Complejidad social',NULL,NULL);
INSERT INTO attribute_desc VALUES(2052,5001,'en','Social frontiers','Social frontiers',NULL,NULL);
INSERT INTO attribute_desc VALUES(2052,5001,'es','Fronteras sociales','Fronteras sociales',NULL,NULL);
INSERT INTO attribute_desc VALUES(2053,5001,'en','Social studies of CTS','Social studies of CTS',NULL,NULL);
INSERT INTO attribute_desc VALUES(2053,5001,'es','Estudios CTS','Estudios Sociales  y Filosóficos de la Ciencia y la Tecnología',NULL,NULL);
INSERT INTO attribute_desc VALUES(2054,5001,'en','Socio-ecology','Socio-ecology',NULL,NULL);
INSERT INTO attribute_desc VALUES(2054,5001,'es','Socioecologia','Socioecología',NULL,NULL);
INSERT INTO attribute_desc VALUES(2055,5001,'en','Socio-history of quantification','Socio-history of quantification',NULL,NULL);
INSERT INTO attribute_desc VALUES(2055,5001,'es','Socio-historia de la cuantificacion','Socio-historia de la cuantificación',NULL,NULL);
INSERT INTO attribute_desc VALUES(2056,5001,'en','Sociology of professions','Sociology of Professions',NULL,NULL);
INSERT INTO attribute_desc VALUES(2056,5001,'es','Sociologia de las profesiones','Sociología de las profesiones',NULL,NULL);
INSERT INTO attribute_desc VALUES(2057,5001,'en','Concept networks','Concept networks',NULL,NULL);
INSERT INTO attribute_desc VALUES(2057,5001,'es','Redes conceptuales','Redes conceptuales','Epistemología estructural del conocimiento',NULL);
INSERT INTO attribute_desc VALUES(2058,5001,'en','Study of News','Study of News and Financial Markets',NULL,NULL);
INSERT INTO attribute_desc VALUES(2058,5001,'es','Estudio de Noticias y Mercados Financieros','Estudio de Noticias y Mercados Financieros',NULL,NULL);
INSERT INTO attribute_desc VALUES(2059,5001,'en','University s sociocultural history','University’s sociocultural history',NULL,NULL);
INSERT INTO attribute_desc VALUES(2059,5001,'es','Historia sociocultural universitaria','Historia sociocultural universitaria',NULL,NULL);
INSERT INTO attribute_desc VALUES(2060,5001,'en','Resilience','Resilience',NULL,NULL);
INSERT INTO attribute_desc VALUES(2060,5001,'es','Resilencia','Resilencia',NULL,NULL);
INSERT INTO attribute_desc VALUES(2061,5001,'en','Academic entities','Academic Entities, Spaces, and Networks',NULL,NULL);
INSERT INTO attribute_desc VALUES(2061,5001,'es','Entidades Academicas','Entidades, Espacios y Redes Académicas',NULL,NULL);
INSERT INTO attribute_desc VALUES(2062,5001,'en','Agri-food networks','Agri-food Networks',NULL,NULL);
INSERT INTO attribute_desc VALUES(2062,5001,'es','Redes agroalimentarias','Redes agroalimentarias',NULL,NULL);
INSERT INTO attribute_desc VALUES(2063,5001,'en','Artificial intelligence','Artificial Intelligence',NULL,NULL);
INSERT INTO attribute_desc VALUES(2063,5001,'es','Inteligencia artificial','Inteligencia artificial',NULL,NULL);
INSERT INTO attribute_desc VALUES(2064,5001,'en','Physical Theories','Astronomy, Cosmology, and Gravitation Theories',NULL,NULL);
INSERT INTO attribute_desc VALUES(2064,5001,'es','Teorias fisicas','Astronomía, Cosmología y Gravitación',NULL,NULL);
INSERT INTO attribute_desc VALUES(2065,5001,'en','Social Measurement','Categories and Classifications of Social Measurement',NULL,NULL);
INSERT INTO attribute_desc VALUES(2065,5001,'es','Medicion social','Las categorías y clasificaciones de medición social',NULL,NULL);
INSERT INTO attribute_desc VALUES(2066,5001,'en','Cetaceans','Cetaceans',NULL,NULL);
INSERT INTO attribute_desc VALUES(2066,5001,'es','Cetaceos','Cetáceos',NULL,NULL);
INSERT INTO attribute_desc VALUES(2067,5001,'en','Climate Change','Climate Change',NULL,NULL);
INSERT INTO attribute_desc VALUES(2067,5001,'es','Cambio climatico','Cambio climático',NULL,NULL);
INSERT INTO attribute_desc VALUES(2068,5001,'en','Information Sources','Comparison of Documents and Information Sources',NULL,NULL);
INSERT INTO attribute_desc VALUES(2068,5001,'es','Cotejos de Documentos','Cotejos de Documentos y fuentes de información',NULL,NULL);
INSERT INTO attribute_desc VALUES(2069,5001,'en','COVID-19','COVID-19',NULL,NULL);
INSERT INTO attribute_desc VALUES(2069,5001,'es','COVID 19','COVID 19',NULL,NULL);
INSERT INTO attribute_desc VALUES(2070,5001,'en','Trajectories of Science','Development and Trajectories of Science and Technology',NULL,NULL);
INSERT INTO attribute_desc VALUES(2070,5001,'es','Trayectorias en CyT','Desarrollo y trayectorias de C y T',NULL,NULL);
INSERT INTO attribute_desc VALUES(2071,5001,'en','Digital News','Digital News and Journalism',NULL,NULL);
INSERT INTO attribute_desc VALUES(2071,5001,'es','Noticias digitales','Noticias digitales, periodismo',NULL,NULL);
INSERT INTO attribute_desc VALUES(2072,5001,'en','Digital Technologies','Digital Technologies',NULL,NULL);
INSERT INTO attribute_desc VALUES(2072,5001,'es','Tecnologias digitales','Tecnologías digitales',NULL,NULL);
INSERT INTO attribute_desc VALUES(2073,5001,'en','Economic System','Economic System and Financial Markets',NULL,NULL);
INSERT INTO attribute_desc VALUES(2073,5001,'es','Sistema Economico','Sistema Económico y Mercados Financieros ',NULL,NULL);
INSERT INTO attribute_desc VALUES(2074,5001,'en','Collective Tasks','Groups of People Working on Collective Tasks',NULL,NULL);
INSERT INTO attribute_desc VALUES(2074,5001,'es','Tareas colectivas','Grupos de personas trabajando en tareas colectivas',NULL,NULL);
INSERT INTO attribute_desc VALUES(2075,5001,'en','Human Vocal Interactions','Human Vocal Interactions',NULL,NULL);
INSERT INTO attribute_desc VALUES(2075,5001,'es','Interacciones vocales humanas','Interacciones vocales humanas',NULL,NULL);
INSERT INTO attribute_desc VALUES(2076,5001,'en','Statistical Practices','Institutionalization Processes of Statistical Practice',NULL,NULL);
INSERT INTO attribute_desc VALUES(2076,5001,'es','Institucionalizacion de la estadistica','Procesos de institucionalización de la práctica de la estadística ',NULL,NULL);
INSERT INTO attribute_desc VALUES(2077,5001,'en','Nanotechnology','Nanotechnology',NULL,NULL);
INSERT INTO attribute_desc VALUES(2077,5001,'es','Nano-tecnologia','Nano-tecnología',NULL,NULL);
INSERT INTO attribute_desc VALUES(2078,5001,'en','Socio-ecosystems in Yucatan','Socio-ecosystems in Yucatan',NULL,NULL);
INSERT INTO attribute_desc VALUES(2078,5001,'es','Socio-ecosistemas en Yucatan','Socio-ecosistemas en Yucatán',NULL,NULL);
INSERT INTO attribute_desc VALUES(2079,5001,'en','Socio-scientific Systems','Socio-technical and Socio-scientific Systems',NULL,NULL);
INSERT INTO attribute_desc VALUES(2079,5001,'es','Sistemas socio-cientificos','Sistemas socio-técnicos y socio-científicos',NULL,NULL);
INSERT INTO attribute_desc VALUES(2080,5001,'en','Spider Monkeys','Spider Monkeys',NULL,NULL);
INSERT INTO attribute_desc VALUES(2080,5001,'es','Monos araña','Monos araña',NULL,NULL);
INSERT INTO attribute_desc VALUES(2081,5001,'en','Studies of Scientists','Studies and Biographies of Scientists',NULL,NULL);
INSERT INTO attribute_desc VALUES(2081,5001,'es','Estudios sobre cientificos','Estudios y biografías sobre científicos',NULL,NULL);
INSERT INTO attribute_desc VALUES(2082,5001,'en','Tourism','Tourism Promotion and Advertising',NULL,NULL);
INSERT INTO attribute_desc VALUES(2082,5001,'es','Turismo','La promoción y publicidad turística',NULL,NULL);
INSERT INTO attribute_desc VALUES(2083,5001,'en','1st period','1st period','1988-1995',NULL);
INSERT INTO attribute_desc VALUES(2083,5001,'es','Periodo 1','Periodo 1','1988-1995',NULL);
INSERT INTO attribute_desc VALUES(2084,5001,'en','2nd period','2nd period','1996-2010',NULL);
INSERT INTO attribute_desc VALUES(2084,5001,'es','Periodo 2','Periodo 2','1996-2010',NULL);
INSERT INTO attribute_desc VALUES(2085,5001,'en','3rd period','3rd period','2011-2025',NULL);
INSERT INTO attribute_desc VALUES(2085,5001,'es','Periodo 3','Periodo 3','2011-2025',NULL);
INSERT INTO attribute_desc VALUES(2086,5001,'en','Postdoctoral','Postdoctoral',NULL,NULL);
INSERT INTO attribute_desc VALUES(2086,5001,'es','Posdoctorales','Posdoctorales',NULL,NULL);
INSERT INTO attribute_desc VALUES(2087,5001,'en','Researcher','Researcher',NULL,NULL);
INSERT INTO attribute_desc VALUES(2087,5001,'es','Investigadores','Investigadores',NULL,NULL);
INSERT INTO attribute_desc VALUES(2088,5001,'en','Technician','Technician',NULL,NULL);
INSERT INTO attribute_desc VALUES(2088,5001,'es','Tecnicos','Técnicos',NULL,NULL);
INSERT INTO attribute_desc VALUES(2089,5001,'en','Short stay','Short visit','Sabatical stays, short visits, short posdoctorates',NULL);
INSERT INTO attribute_desc VALUES(2089,5001,'es','Estancia corta','Estancia corta','Estancias sabáticas, visitas, posdoctorados de uno o dos años.',NULL);
INSERT INTO attribute_desc VALUES(2090,5001,'en','Socio History','Socio-history',NULL,NULL);
INSERT INTO attribute_desc VALUES(2090,5001,'es','Socio-historia','Socio-historia',NULL,NULL);
INSERT INTO attribute_desc VALUES(2091,5001,'en','Studies of technitians','Studies of technicians',NULL,NULL);
INSERT INTO attribute_desc VALUES(2091,5001,'es','Estudios sobre tecnologos','Estudios sobre tecnólogos',NULL,NULL);
